capacitor-community/stripe

ios/Plugin/Plugin.swift
This only affects iOS.
Currently, even though the `confirmSetupIntent` is successful, the plugin just returns an empty JavaScript object `{}` upon success. It is important to get the `paymentMethodId` from a successful confirmation so that the `paymentMethodId` is registered to the Stripe User.
This Pull Request just returns the `paymentMethodId` when `confirmSetupIntent` succeeds. I don't know where to get the other data that the interface `ConfirmSetupIntentResponse` has, however, this should help make `confirmSetupIntent` at least useful in iOS.
=> Return at least paymentMethodId when confirming setupIntent on iOS

android/src/main/java/com/getcapacitor/community/stripe/StripePlugin.java, ios/Plugin/StripePlugin.swift
Hello! I was recently taking inventory of plugins wrapping our iOS and Android SDKs, and I noticed that your plugin isn't sending a user-agent [via the `AppInfo` field](https://stripe.com/docs/building-plugins). Would you mind if I changed this? It would help us provide better support for our users when they call in with integration questions.
I'm not very familiar with Capacitor, so please let me know if this isn't the right place to add this code. Thanks!
=> Send plugin AppInfo

src/shared/index.ts
Ref: #116
The `customerId` prop is not required property in Stripe. So we can change this from required to optional.
We can test this by the following steps.
- Run `npm run build`
- Go to demo app (`demo/angular`)
- Run `npm install`
- Delete these line -> https://github.com/capacitor-community/stripe/blob/feat/no-customer-id/demo/angular/src/app/tab2/tab2.page.ts#L89-L90
- Run `npm start`
- Go to http://localhost:4200/tabs/tab2
- Click "Expect Happy Path"
- Run `npm run build`
- Go to demo app (`demo/angular`)
- Run `npm install`
- Delete these line -> https://github.com/capacitor-community/stripe/blob/feat/no-customer-id/demo/angular/src/app/tab3/tab3.page.ts#L112-L113
- Run `npm start`
- Go to http://localhost:4200/tabs/tab3
- Click "Expect Happy Path"
=> feat: can create PaymentSheet and PaymentFlow without customer id

android/src/main/java/com/getcapacitor/community/stripe/paymentflow/PaymentFlowExecutor.java, android/src/main/java/com/getcapacitor/community/stripe/paymentsheet/PaymentSheetExecutor.java, demo/angular/ios/App/App.xcodeproj/project.pbxproj, demo/angular/ios/App/App/App.entitlements, demo/angular/src/app/tab1/tab1.page.html, demo/angular/src/app/tab1/tab1.page.ts, demo/angular/src/app/tab2/tab2.page.ts, demo/angular/src/app/tab3/tab3.page.ts, demo/react/src/hooks/payment-sheet.ts, demo/server/.eslintrc.js, demo/server/src/app.controller.ts, ios/Plugin/PaymentFlow/PaymentFlowExecutor.swift, ios/Plugin/PaymentSheet/PaymentSheetExecutor.swift, package.json
fix https://github.com/capacitor-community/stripe/issues/162
=> fix(): to be customer optional 

android/src/main/java/com/getcapacitor/community/stripe/googlepay/GooglePayExecutor.java
Update GooglePayExecutor.java to support both payment intents and setup intents. This is already supported in the Apple Pay implementation.
=> Add support for setup intents to Google Pay

android/src/main/java/com/getcapacitor/community/stripe/StripePlugin.java
We have a need to work with different stripe accounts in one application. With each payment, we change and initialize different public keys from different companies. But initialization worked painlessly only on ios, on android we found a small flaw in the plugin code. 
If you remove the check for an empty publishableKey, then everything works as it should) 
If possible, please add this to the update or if you have any ideas on how to improve and secure the code, I will be glad to any suggestions
=> remove only one key initialization condition

CapacitorCommunityStripe.podspec, README.md, android/build.gradle, android/src/main/java/com/getcapacitor/community/stripe/StripePlugin.java, android/src/main/java/com/getcapacitor/community/stripe/identityverification/IdentityVerificationSheetEvent.kt, android/src/main/java/com/getcapacitor/community/stripe/identityverification/IdentityVerificationSheetExecutor.java, ios/Plugin.xcodeproj/project.pbxproj, ios/Plugin/IdentityVerificationSheet/IdentityVerificationSheetEvents.swift, ios/Plugin/IdentityVerificationSheet/IdentityVerificationSheetExecutor.swift, ios/Plugin/StripePlugin.m, ios/Plugin/StripePlugin.swift, ios/Podfile, src/definitions.ts, src/identityverificationsheet/identity-verification-sheet-definitions.interface.ts, src/identityverificationsheet/identity-verification-sheet-events.enum.ts, src/identityverificationsheet/index.ts, src/web.ts
I've added [Stripe Identity functionality](https://stripe.com/docs/identity/verify-identity-documents) to the plugin for both Android & iOS. Web is not supported.
- Adds `createIdentityVerificationSheet` and `presentIdentityVerificationSheet`
- A 32x32 icon is required by Stripe Identity - this implementation passes through the Android or iOS app icon
- Per [integration documentation](https://stripe.com/docs/identity/verify-identity-documents) a `VerificationSession` and an `EphemeralKey` needs to be created server-side before calling `createIdentityVerificationSheet` which takes those values as parameters:
```typescript
const { ephemeralKeySecret, verificationId } = await createVerificationSession()
await Stripe.createIdentityVerificationSheet({
ephemeralKeySecret,
verificationId,
})
try …
```
=> Add Stripe Identity

android/src/main/java/com/getcapacitor/community/stripe/StripePlugin.java, android/src/main/java/com/getcapacitor/community/stripe/helper/MetaData.java
Added metadata options to specify what, if any, billing info to require from Google Pay. Add the following entries to `strings.xml` in the Android project to enable additional data:
```
<bool name="email_address_required">true</bool>
<bool name="phone_number_required">true</bool>
<bool name="billing_address_required">true</bool>
<string name="billing_address_format">Full</string>
```
Billing address format can be set to `Full` or `Min`. If the metadata properties are omitted, the data will simply not be requested (same as current plugin behavior).
=> Add support for getting billing info from Google Pay

android/build.gradle
Because some times kotlin read jvm 18 but the java still 17 wil cause error:
* What went wrong: 
Execution failed for task ':capacitor-community-stripe:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 18) jvm target compatibility should be set to the same Java version. Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
=> Update build.gradle kotlin jvmTarget to 17

packages/identity/CapacitorCommunityStripeIdentity.podspec, packages/identity/README.md, packages/identity/android/build.gradle
Thanks for building the capacitor plugin for Stripe Identity! This PR fixed a small typo in README and added a section to add camera permission on iOS, also added details links to the native SDK.
For our react native wrapper, we pick up the latest Android/iOS minor version instead of using a fixed version, also made similar changes here.
=> [Identity] Update readme and the native versions with latest minor

packages/payment/README.md, packages/payment/android/src/main/java/com/getcapacitor/community/stripe/paymentsheet/PaymentSheetExecutor.java, packages/payment/ios/Plugin/PaymentSheet/PaymentSheetExecutor.swift, packages/payment/src/shared/index.ts
This PR adds the ability to include additional billing details (email, name, phone, address) to show up on the PaymentSheet.
However, the available options for email, phone, name collection are only `always` and `automatic` and for address `full` and `automatic`. This has been done to minimize the impact of the changes and to also be scalable if other collection modes are to be made available.
=> Add extra billing details to payment sheet

packages/payment/ios/Plugin/ApplePay/ApplePayExecutor.swift, packages/payment/src/shared/index.ts
Hello again @rdlabo.
I'm Rubén García de Longoria, a little over a year ago I made [this PR](https://github.com/capacitor-community/stripe/pull/210) PR to add the shipping address functionality.
Now I come to propose a new improvement that we have implemented in our App.
Our App sells ecological products to different countries. The final price varies depending on the destination country.
The user has selected a destination country in the App, but the Apple Pay address may be from a different country.
The problem is that the plugin, although it has the didSelectShippingContact event to detect this change in JavaScript, there is no possibility of modifying the figure in Apple Pay once opened. It would have to be developed natively within the plugin.
What we do is prohibit the user from …
=> feat: add logic to allow countries and block others

packages/payment/README.md, packages/payment/android/build.gradle, packages/payment/package.json
Issue:
- https://github.com/capacitor-community/stripe/issues/331
- https://github.com/ionic-team/capacitor-plugins/issues/1994
Please try this version:
```
% npm install @capacitor-community/stripe@5.4.3-1
```
=> fix(payment): default android version must be support 33

packages/identity/CapacitorCommunityStripeIdentity.podspec, packages/identity/ios/Podfile, packages/payment/CapacitorCommunityStripe.podspec, packages/payment/ios/Podfile
Reverts capacitor-community/stripe#337
This pull request is require iOS 15+. 
> minimum deployment target
=> Revert "bump iOS to `~> 23.24.0` and Android to `20.38.+`"

demo/angular/src/app/terminal/terminal.page.ts, packages/terminal/README.md, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminal.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminalPlugin.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/TerminalEvent.kt, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/TokenProvider.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/helper/MetaData.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/models/Executor.java, packages/terminal/ios/Plugin/StripeTerminal.swift, packages/terminal/ios/Plugin/StripeTerminalPlugin.m, packages/terminal/ios/Plugin/StripeTerminalPlugin.swift, packages/terminal/ios/Plugin/TerminalEvents.swift, packages/terminal/ios/PluginTests/StripeTerminalTests.swift, packages/terminal/src/definitions.ts, packages/terminal/src/events.enum.ts, packages/terminal/src/web.ts
close https://github.com/capacitor-community/stripe/issues/335
```typescript
(async ()=> {
/**
* tokenProviderEndpoint: The URL of your backend to provide a token. Use Post request to get a token.
*/
await StripeTerminal.initialize({ tokenProviderEndpoint: 'https://example.com/token', isTest: true })
const { readers } = await StripeTerminal.discoverReaders({
type: TerminalConnectTypes.TapToPay,
locationId: "**************",
});
await StripeTerminal.connectReader({
reader: readers[0],
});
await StripeTerminal.collect({ paymentIntent: "**************" });
});
```
```typescript
(async ()=> {
// run before StripeTerminal.initialize
StripeTerminal.addListener(TerminalEventsEnum.RequestedConnectionToken, async () => {
const { token } = (await fetch("https://example.com/token")).json(); …
```
=> feat(terminal): add option to set string token

demo/angular/android/app/src/main/AndroidManifest.xml, demo/angular/android/variables.gradle, demo/angular/ios/App/Podfile.lock, demo/angular/src/app/terminal/terminal.page.ts, demo/angular/src/environments/environment.ts, packages/terminal/CapacitorCommunityStripeTerminal.podspec, packages/terminal/README.md, packages/terminal/android/build.gradle, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminal.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminalPlugin.java, packages/terminal/ios/Plugin/StripeTerminal.swift, packages/terminal/ios/Plugin/StripeTerminalPlugin.m, packages/terminal/ios/Plugin/StripeTerminalPlugin.swift, packages/terminal/ios/Podfile, packages/terminal/package.json, packages/terminal/src/definitions.ts, packages/terminal/src/web.ts
related: https://github.com/capacitor-community/stripe/pull/342
---
---
minSdk require 30: https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md?fbclid=IwAR1xPmIwpEub42qXqihB2szcU_pstuLxnUcCgV8v8LtuEQqtyiYkfYa7Ql0#tap-to-pay-localmobile-1
=> feat(terminal): rename collect to collectPaymentMethod

demo/angular/android/app/src/main/AndroidManifest.xml, demo/angular/android/app/src/main/res/values/strings.xml, demo/react/android/app/src/main/AndroidManifest.xml, demo/react/android/app/src/main/res/values/strings.xml, packages/payment/android/src/main/java/com/getcapacitor/community/stripe/StripePlugin.java, packages/payment/android/src/main/java/com/getcapacitor/community/stripe/helper/MetaData.java, packages/payment/package.json
Related: https://github.com/capacitor-community/stripe/issues/329
```
If true, Google Pay is considered ready if the customer's Google Pay wallet has existing payment methods.
Default to true.
```
AndroidManifest.xml:
```diff
+        <meta-data
+            android:name="com.getcapacitor.community.stripe.google_pay_existing_payment_method_required"
+            android:value="@bool/google_pay_existing_payment_method_required"/>
```
string.xml
```diff
<bool name="google_pay_existing_payment_method_required">false</bool>
```
=> feat(payment): add google_pay_existing_payment_method_required to Manifest at Google Pay

packages/terminal/README.md, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminal.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminalPlugin.java, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/TerminalEvent.kt, packages/terminal/src/definitions.ts, packages/terminal/src/events.enum.ts, packages/terminal/src/stripe.enum.ts, packages/terminal/src/web.ts
Adds new events to report reader software update status, an event to report reader battery status, and setSimulatorConfiguration method.
=> android: feat(terminal): add bindings for reader software update status, battery level, and simulator configuration

packages/payment/ios/Sources/StripePlugin/ApplePay/ApplePayExecutor.swift
I made a correction in the STPApplePayContext.swift due to the guard statement being triggered by nil values.
Here is the relevant:
https://github.com/stripe/stripe-ios/blob/6a12711bfffae39034608b7fa4ad36cf90cdbe59/StripeApplePay/StripeApplePay/Source/ApplePayContext/STPApplePayContext.swift#L556
=> ios: fix: initial error value for apple pay

packages/payment/android/src/main/java/com/getcapacitor/community/stripe/StripePlugin.kt
The commit f1ddf70 changed the way as `metaData` initializes, but `this.context` is not ready to be used until `load()` is called, which MetaData always fails when initializing
=> fix(android): metadata could not be loaded because context was not ready yet

packages/terminal/README.md, packages/terminal/android/build.gradle, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/StripeTerminal.kt, packages/terminal/android/src/main/java/com/getcapacitor/community/stripe/terminal/TerminalConnectTypes.kt, packages/terminal/src/stripe.enum.ts
PR for https://github.com/capacitor-community/stripe/issues/421
- Added new type `hand-off` in the **TerminalConnectTypes**
- Created a function to discover and connect to a reader using the `HandoffConnectionConfiguration`
- None since hand off configuration is only for Stripe Android devices
@rdlabo
=> feat(terminal): Implemented handoff connection type

packages/terminal/src/web.ts
The unavailable function returns a CapacitorError that needs to be thrown
=> Throw unavailable when not using Internet type on the web

packages/payment/src/shared/index.ts
Allow AddressCollectionMode: never in BillingDetailsCollectionConfiguration for BasePaymentOption.
This aligns with the SDKs
=> fix(payment): BillingDetailsCollectionConfiguration: AddressCollectionMode: never

README.md
Issue identified in #440 which requires latest versions of stripe sdk. Updating the README to reflect this.
=> #440 Update README.md to increase Stripe SDK verison for Stripe Terminal.
